#!/bin/sh

if [ $# -gt 0 ]
then
  files="$*"
else
  files="
	startll

        initc
       
        messages
        toplevel
        files
        module
        defs
        genarith

        path
        llpboot
        setf
        defstruct
        abbrev
        microceyx
        debug
        trace
        pretty

        libcir
        sort
        array
        callext
        format
        date

        libdate
        sets
        hash
        stringio

        virtty
        vt100

        resetfn

        schedule
        product
"
fi

echo "Making C code for files: $files"

../../linux/complice <<EOI
(loadfile "../C/modtoc.lo"  t)


(setq #:modtoc:use-threshold-read-only  2)  ; 2
(setq #:modtoc:use-threshold-read-write 3)  ; 3

(setq #:modtoc:peephole-optimize-p       t)
(setq #:modtoc:optimize-local-labels-p   t)

(setq #:modtoc:stats-on-C-size-p         t)
(setq #:modtoc:peephole-debug            ())
(setq #:modtoc:doit-debug                ())
(setq #:modtoc:C-verbose-mode            ())

(defun makeCllib ()
   (let ((#:system:path (mcons "New/" 
                               "../C/"
                                "../../llib/"
                                "../../llub/"
                                "../../llobj/"
                                "../../llmod/"
                                #:system:path)))

        (mapc  (quote module-to-C) (quote ($files)) )
'        (mapc  (quote module-to-C) (quote (initc)) )
   ))



(makeCllib)
(#:modtoc:stats-global)
(end)

EOI


echo "translation done."
mv *.le /nfs/lelisp15/work/Celab
echo "elaboration files copied on Celab."
