# This makefile was generated by the ILOG Runtime Generator.
# Version     : 2         Date : Tue Oct  19 93 16:02:39 
# SubVersion  : 2
# It enables to build modules from Lisp source files for 
# - project : ll2lm
#
# 
# 
# Project name      : ll2lm
# Root directory    : /nfs/lelisp15/work/ll2lm/
# References file   : #p"/nfs/lelisp15/work/ll2lm/ll2lm.ref"
# Runtime directory : /nfs/lelisp15/work/ll2lm/
# Bin directory     : /nfs/lelisp15/work/ll2lm/sun4/
# System directory  : /nfs/lelisp15/work/ll2lm/
# Directories       :    ("/nfs/lelisp15/work/ll2lm/" "/nfs/lelisp15/work/llyze/")
# Modules lists     : (all)
# Modules           : ()
# Modules required  : ()
# Exclude modules   : ()
# [CRUNCH] Crunch directory  : /nfs/lelisp15/work/ll2lm/
# [COMPLICE] LLOBJS directories : 
# [COMPLICE] COMPLICEFLAGS      : 
# 
# 
######
# Directories
######

LLDIR=..
LL2LMDIR=$(LLDIR)/ll2lm
SRCDIR=$(LLDIR)/ll2lm
LLIBDIR=$(LLDIR)/llib
SYSTEM=sun4

COMPLICEDIRS=\"$(LL2LMDIR)/\" \"$(SRCDIR)/\"
######
# Make use of standard complice
# No path is set, we recommend you to install the complice
# command in /usr/local/bin for example
######

#COMPLICE=/usr/ilog/lelisp/$(SYSTEM)/complice
COMPLICE=/nfs/current/lelisp/$(SYSTEM)/complice

######
# Complice options
######

COMPLICEFLAGS=\
	-e "(set (symbol 'system 'path) (append '(\"\") '($(COMPLICEDIRS)) (symeval (symbol 'system 'path))))" 

######
# LL Objects involved
######

LLOBJS= $(LL2LMDIR)/defvar.lo \
	$(LL2LMDIR)/syserror.lo \
	$(LL2LMDIR)/crunch.lo \
	$(LL2LMDIR)/parse.lo \
	$(LL2LMDIR)/printlm.lo \
	$(LL2LMDIR)/diagnostic.lo \
	$(LL2LMDIR)/codewalker.lo \
	$(LL2LMDIR)/readlm.lo \
	$(LL2LMDIR)/ref.lo \
	$(LL2LMDIR)/kernellm.lo \
	$(LL2LMDIR)/rtprint.lo \
	$(LL2LMDIR)/rtmsg.lo \
	$(LL2LMDIR)/defrtprj.lo \
	$(LL2LMDIR)/create.lo \
	$(LL2LMDIR)/make.lo \
	$(LL2LMDIR)/merge.lo \
	$(LL2LMDIR)/meta.lo \
	$(LL2LMDIR)/delete.lo \
	$(LL2LMDIR)/build.lo

######
# Generic entries
######

all: $(LLOBJS)

clean:
	rm -f $(LLOBJS)

info:
	@echo complice=$(COMPLICE)
	@echo Directories used for complice are : 
	@echo $(COMPLICEDIRS)
	@echo compliceflags=$(COMPLICEFLAGS)

i:
	$(COMPLICE) $(COMPLICEFLAGS) -i -v

######
# Module dependencies
######
ll2lm: ll2lm-sh
$(LL2LMDIR)/ll2lm-sh ll2lm-sh: $(LL2LMDIR)/ll2lm.conf $(LL2LMDIR)/crunch.lo
	$(LLDIR)/$(SYSTEM)/config ll2lm-sh $(LLDIR)/$(SYSTEM)/lelispbin \
		$(LL2LMDIR)/ll2lm.conf \
		$(LL2LMDIR) \
		-stack 6 -code 800 -heap 1000 -vector 5 -string 10 -symbol 10 -cons 10

ll2lm-: ll2lm--sh
$(LL2LMDIR)/ll2lm--sh ll2lm--sh: $(LL2LMDIR)/ll2lm-.conf $(LL2LMDIR)/crunch.lo
	$(LLDIR)/$(SYSTEM)/config ll2lm--sh $(LLDIR)/$(SYSTEM)/lelispbin \
		$(LL2LMDIR)/ll2lm-.conf \
		$(LL2LMDIR) \
		-stack 6 -code 800 -heap 1000 -vector 5 -string 10 -symbol 10 -cons 10

$(LL2LMDIR)/syserror.lo syserror.lo: \
	$(LL2LMDIR)/syserror.lc \
	$(SRCDIR)/syserror.ll \
	$(LL2LMDIR)/defvar.lo \
	$(LL2LMDIR)/rtprint.lo \
	$(LL2LMDIR)/rtmsg.lo \
	$(LL2LMDIR)/ref.lo
	@echo "+++++ COMPLICE : " \
	$(LL2LMDIR)/syserror.lm 
	@cp $(LL2LMDIR)/syserror.lc $(LL2LMDIR)/syserror.lm 
	@cd $(LL2LMDIR)/ ; $(COMPLICE) syserror \
	$(COMPLICEFLAGS) 

$(LL2LMDIR)/crunch.lo crunch.lo: \
	$(LL2LMDIR)/crunch.lc \
	$(SRCDIR)/crunch.ll \
	$(LL2LMDIR)/defvar.lo \
	$(LL2LMDIR)/kernellm.lo \
	$(LL2LMDIR)/rtprint.lo \
	$(LL2LMDIR)/diagnostic.lo \
	$(LL2LMDIR)/ref.lo \
	$(LL2LMDIR)/parse.lo \
	$(LL2LMDIR)/printlm.lo \
	$(LL2LMDIR)/rtmsg.lo \
	$(LL2LMDIR)/defrtprj.lo \
	$(LL2LMDIR)/create.lo \
	$(LL2LMDIR)/make.lo \
	$(LL2LMDIR)/meta.lo \
	$(LL2LMDIR)/delete.lo \
	$(LL2LMDIR)/build.lo 
	@echo "+++++ COMPLICE : " $(LL2LMDIR)/crunch.lm 
	@cp $(LL2LMDIR)/crunch.lc $(LL2LMDIR)/crunch.lm 
	@cd $(LL2LMDIR)/ ; $(COMPLICE) crunch \
	$(COMPLICEFLAGS) 

$(LL2LMDIR)/parse.lo parse.lo: \
	$(LL2LMDIR)/parse.lc \
	$(SRCDIR)/parse.ll \
	$(LL2LMDIR)/defvar.lo \
	$(LL2LMDIR)/kernellm.lo \
	$(LL2LMDIR)/syserror.lo \
	$(LL2LMDIR)/rtmsg.lo \
	$(LL2LMDIR)/ref.lo
	@echo "+++++ COMPLICE : " $(LL2LMDIR)/parse.lm 
	@cp $(LL2LMDIR)/parse.lc $(LL2LMDIR)/parse.lm 
	@cd $(LL2LMDIR)/ ; $(COMPLICE) parse \
	$(COMPLICEFLAGS) 

$(LL2LMDIR)/printlm.lo printlm.lo: \
	$(LL2LMDIR)/printlm.lc \
	$(SRCDIR)/printlm.ll \
	$(LL2LMDIR)/defvar.lo \
	$(LL2LMDIR)/kernellm.lo \
	$(LL2LMDIR)/diagnostic.lo
	@echo "+++++ COMPLICE : " \
	$(LL2LMDIR)/printlm.lm 
	@cp $(LL2LMDIR)/printlm.lc $(LL2LMDIR)/printlm.lm 
	@cd $(LL2LMDIR)/ ; $(COMPLICE) printlm \
	$(COMPLICEFLAGS) 

$(LL2LMDIR)/diagnostic.lo diagnostic.lo: \
	$(LL2LMDIR)/diagnostic.lc \
	$(SRCDIR)/diagnostic.ll \
	$(LL2LMDIR)/defvar.lo \
	$(LL2LMDIR)/rtprint.lo \
	$(LL2LMDIR)/kernellm.lo 
	@echo "+++++ COMPLICE : " \
	$(LL2LMDIR)/diagnostic.lm 
	@cp $(LL2LMDIR)/diagnostic.lc $(LL2LMDIR)/diagnostic.lm 
	@cd $(LL2LMDIR)/ ; $(COMPLICE) diagnostic \
	$(COMPLICEFLAGS) 

$(LL2LMDIR)/codewalker.lo codewalker.lo: \
	$(LL2LMDIR)/codewalker.lc \
	$(SRCDIR)/codewalker.ll \
	$(LL2LMDIR)/defvar.lo \
	$(LL2LMDIR)/kernellm.lo \
	$(LL2LMDIR)/rtprint.lo \
	$(LL2LMDIR)/diagnostic.lo \
	$(LL2LMDIR)/ref.lo \
	$(LL2LMDIR)/parse.lo \
	$(LL2LMDIR)/printlm.lo \
	$(LL2LMDIR)/rtmsg.lo \
	$(LL2LMDIR)/defrtprj.lo
	@echo "+++++ COMPLICE : " $(LL2LMDIR)/codewalker.lm 
	@cp $(LL2LMDIR)/codewalker.lc $(LL2LMDIR)/codewalker.lm 
	@cd $(LL2LMDIR)/ ; $(COMPLICE) codewalker \
	$(COMPLICEFLAGS) 

$(LL2LMDIR)/readlm.lo readlm.lo: \
	$(LL2LMDIR)/readlm.lc \
	$(SRCDIR)/readlm.ll \
	$(LL2LMDIR)/defvar.lo \
	$(LL2LMDIR)/kernellm.lo \
	$(LL2LMDIR)/rtprint.lo
	@echo "+++++ COMPLICE : " \
	$(LL2LMDIR)/readlm.lm 
	@cp $(LL2LMDIR)/readlm.lc $(LL2LMDIR)/readlm.lm 
	@cd $(LL2LMDIR)/ ; $(COMPLICE) readlm \
	$(COMPLICEFLAGS) 

$(LL2LMDIR)/ref.lo ref.lo: \
	$(LL2LMDIR)/ref.lc \
	$(SRCDIR)/ref.ll \
	$(LL2LMDIR)/defvar.lo \
	$(LL2LMDIR)/kernellm.lo \
	$(LL2LMDIR)/readlm.lo \
	$(LL2LMDIR)/diagnostic.lo
	@echo "+++++ COMPLICE : " \
	$(LL2LMDIR)/ref.lm 
	@cp $(LL2LMDIR)/ref.lc $(LL2LMDIR)/ref.lm 
	@cd $(LL2LMDIR)/ ; $(COMPLICE) ref \
	$(COMPLICEFLAGS) 

$(LL2LMDIR)/kernellm.lo kernellm.lo: \
	$(LL2LMDIR)/kernellm.lc \
	$(SRCDIR)/kernellm.ll 
	@echo "+++++ COMPLICE : " \
	$(LL2LMDIR)/kernellm.lm 
	@cp $(LL2LMDIR)/kernellm.lc $(LL2LMDIR)/kernellm.lm 
	@cd $(LL2LMDIR)/ ; $(COMPLICE) kernellm \
	$(COMPLICEFLAGS) 

$(LL2LMDIR)/rtprint.lo rtprint.lo: \
	$(LL2LMDIR)/rtprint.lc \
	$(SRCDIR)/rtprint.ll \
	$(LL2LMDIR)/defvar.lo \
	$(LL2LMDIR)/rtmsg.lo 
	@echo "+++++ COMPLICE : " \
	$(LL2LMDIR)/rtprint.lm 
	@cp $(LL2LMDIR)/rtprint.lc $(LL2LMDIR)/rtprint.lm 
	@cd $(LL2LMDIR)/ ; $(COMPLICE) rtprint \
	$(COMPLICEFLAGS) 

$(LL2LMDIR)/rtmsg.lo rtmsg.lo: \
	$(LL2LMDIR)/rtmsg.lc \
	$(SRCDIR)/rtmsg.ll 
	@echo "+++++ COMPLICE : " $(LL2LMDIR)/rtmsg.lm 
	@cp $(LL2LMDIR)/rtmsg.lc $(LL2LMDIR)/rtmsg.lm 
	@cd $(LL2LMDIR)/ ; $(COMPLICE) rtmsg \
	$(COMPLICEFLAGS) 

$(LL2LMDIR)/defrtprj.lo defrtprj.lo: \
	$(LL2LMDIR)/defrtprj.lc \
	$(SRCDIR)/defrtprj.ll \
	$(LL2LMDIR)/defvar.lo \
	$(LL2LMDIR)/ref.lo
	@echo "+++++ COMPLICE : " $(LL2LMDIR)/defrtprj.lm 
	@cp $(LL2LMDIR)/defrtprj.lc $(LL2LMDIR)/defrtprj.lm 
	@cd $(LL2LMDIR)/ ; $(COMPLICE) defrtprj \
	$(COMPLICEFLAGS) 

$(LL2LMDIR)/make.lo make.lo: \
	$(LL2LMDIR)/make.lc \
	$(SRCDIR)/make.ll \
	$(LL2LMDIR)/defvar.lo \
	$(LL2LMDIR)/codewalker.lo \
	$(LL2LMDIR)/ref.lo \
	$(LL2LMDIR)/rtprint.lo \
	$(LL2LMDIR)/defrtprj.lo \
	$(LL2LMDIR)/diagnostic.lo \
	$(LL2LMDIR)/rtmsg.lo
	@echo "+++++ COMPLICE : " $(LL2LMDIR)/make.lm 
	@cp $(LL2LMDIR)/make.lc $(LL2LMDIR)/make.lm 
	@cd $(LL2LMDIR)/ ; $(COMPLICE) make \
	$(COMPLICEFLAGS) 

$(LL2LMDIR)/merge.lo merge.lo: \
	$(LL2LMDIR)/merge.lc \
	$(SRCDIR)/merge.ll \
	$(LL2LMDIR)/ref.lo \
	$(LL2LMDIR)/rtmsg.lo
	@echo "+++++ COMPLICE : " $(LL2LMDIR)/merge.lm 
	@cp $(LL2LMDIR)/merge.lc $(LL2LMDIR)/merge.lm 
	@cd $(LL2LMDIR)/ ; $(COMPLICE) merge \
	$(COMPLICEFLAGS) 

$(LL2LMDIR)/create.lo create.lo: \
	$(LL2LMDIR)/create.lc \
	$(SRCDIR)/create.ll \
	$(LL2LMDIR)/defvar.lo \
	$(LL2LMDIR)/make.lo \
	$(LL2LMDIR)/rtmsg.lo
	@echo "+++++ COMPLICE : " $(LL2LMDIR)/create.lm 
	@cp $(LL2LMDIR)/create.lc $(LL2LMDIR)/create.lm 
	@cd $(LL2LMDIR)/ ; $(COMPLICE) create \
	$(COMPLICEFLAGS) 

$(LL2LMDIR)/meta.lo meta.lo: \
	$(LL2LMDIR)/meta.lc \
	$(SRCDIR)/meta.ll \
	$(LL2LMDIR)/defvar.lo \
	$(LL2LMDIR)/ref.lo \
	$(LL2LMDIR)/defrtprj.lo \
	$(LL2LMDIR)/diagnostic.lo \
	$(LL2LMDIR)/rtmsg.lo
	@echo "+++++ COMPLICE : " $(LL2LMDIR)/meta.lm 
	@cp $(LL2LMDIR)/meta.lc $(LL2LMDIR)/meta.lm 
	@cd $(LL2LMDIR)/ ; $(COMPLICE) meta \
	$(COMPLICEFLAGS) 

$(LL2LMDIR)/delete.lo delete.lo: \
	$(LL2LMDIR)/delete.lc \
	$(SRCDIR)/delete.ll \
	$(LL2LMDIR)/defvar.lo \
	$(LL2LMDIR)/ref.lo \
	$(LL2LMDIR)/kernellm.lo \
	$(LL2LMDIR)/rtmsg.lo
	@echo "+++++ COMPLICE : " $(LL2LMDIR)/delete.lm 
	@cp $(LL2LMDIR)/delete.lc $(LL2LMDIR)/delete.lm 
	@cd $(LL2LMDIR)/ ; $(COMPLICE) delete \
	$(COMPLICEFLAGS) 

$(LL2LMDIR)/build.lo build.lo: \
	$(LL2LMDIR)/build.lc \
	$(SRCDIR)/build.ll \
	$(LL2LMDIR)/defvar.lo \
	$(LL2LMDIR)/ref.lo \
	$(LL2LMDIR)/defrtprj.lo \
	$(LL2LMDIR)/rtmsg.lo \
	$(LL2LMDIR)/parse.lo
	@echo "+++++ COMPLICE : " $(LL2LMDIR)/build.lm 
	@cp $(LL2LMDIR)/build.lc $(LL2LMDIR)/build.lm 
	@cd $(LL2LMDIR)/ ; $(COMPLICE) build \
	$(COMPLICEFLAGS) 

$(LL2LMDIR)/defvar.lo defvar.lo: \
	$(LL2LMDIR)/defvar.lc \
	$(SRCDIR)/defvar.ll 
	@echo "+++++ COMPLICE : " $(LL2LMDIR)/defvar.lm 
	@cp $(LL2LMDIR)/defvar.lc $(LL2LMDIR)/defvar.lm 
	@cd $(LL2LMDIR)/ ; $(COMPLICE) defvar \
	$(COMPLICEFLAGS) 

