#!/bin/sh

###
### Ce shell-script doit e^tre lance' depuis le re'pertoire lelisp/$machine
### en tapant :
### $ ../lltest/bvx11test
### ... ou depuis aida$machine en tapant :
### $ [/usr/ilog]/lelisp/lltest/bvx11test aida

thehost=`hostname`
theone=${LOGNAME-$USER}
thecomm=${1-'./lelispX11'}
logfile=bv"$thehost".log
testdir=/nfs/work/aida/test


###
### Pour e^tre le moins possible de'pendant de l'environnement, on cre'e
### des .XXX tre`s spe'ciaux :

### 1) un .lelisp

cat > "$testdir/.lelisp" << EOI
;;;
;;; Ce .lelisp a e'te' gene're' par la commande bvrecette
(let ((#:sys-package:tty 'tty)) (print ".lelisp de test"))
(unless (featurep 'aida)
	(libload "testbv.ll")
	(end)) ; tres important...
EOI


### 2) un .aida

cat > "$testdir/.aida" << EOI
;;;
;;; Un .aida tres special pour la recette.
;;; Il termine l'appel a aida-run en la relancant une seconde fois...

(let ((#:sys-package:tty 'tty)) (print ".aida de test"))
(defun user-homedir-pathname () #u"/fhjahjdhg") ; pourvu qu'il n'existe pas
(aida-run "Passage des test du BV sous Aida...")
(libload "testbv.ll")
(end) ; tres important..
EOI


### 3) un .masai (pour les pervers).

cat > "$testdir/.masai" << EOI
;;;
;;; Ce .masai a e'te' gene're' par la commande bvrecette
(let ((#:sys-package:tty 'tty)) (print ".masai de test"))
EOI


### 4) un .Xdefault (pour certaines machines comme l'IBM RT).

cat > "$testdir/.Xdefaults" << EOI
lelisp.font:8x13
lelisp.attributefont:8x13bold
lelisp.largefont:9x15
lelisp.smallfont:6x10
EOI



HOME="$testdir"
export HOME

echo "Passage des tests automatiques du BV. Veuillez patienter..."


###
### On lance avec une trace dans le fichier logfile.

(echo "Test effectue par $theone sur $thehost avec DISPLAY = $DISPLAY" ; $thecomm) | tee $logfile

echo "Re'sultats dans le fichier" $logfile
