#! /bin/sh
################################################################
#
#		Le shell-script de l'expanseur
#			LLM3 -> SPARC
#
################################################################

tmp="/tmp/llexpand$$"
trap "rm -f $tmp; exit" 0 1 2 3 15
echo "(setq #:expand:re-defvalue t)" >>$tmp

# Les valeurs par defaut:
BOOTLISP="/usr/local/bin/complice -i 15"
 echo "(defvar #:expand:s-dir \"./s/\")" 	>> $tmp
 echo "(defvar #:llm3:dir-source \"../llm3/\")"	>> $tmp

while test x$1 != x
do
    case $1 in
# Pour choisir son Lisp d'amorcage:
	-bootlisp)
		BOOTLISP="$2"
		shift ;;
# Pour loader des fichiers:
	-load)	
		echo "(load \"$2\" )"				>> $tmp
		shift ;;
# Pour aller chercher les sources:
	-source)
		echo "(defvar #:llm3:dir-source \"$2\" )"	>> $tmp
		shift ;;
# Pour ranger les expansions:
	-dest)
		echo "(defvar #:expand:s-dir  \"$2\" )"		>> $tmp
		shift ;;
# Pour (re)definir des valeur Lisp:
	-val)
		echo "(defvar $2 $3 )"				>> $tmp
		shift ; shift ;;
# Pour (re)positionner des flags d'expansion:
	-flag)
 		echo "(defvalue $2 $3)"				>> $tmp
		shift ; shift ;;
# Pour expanser d'autres fichiers:
	-files)
		echo "(defvar #:llm3:files '($2))"		>> $tmp
		shift ;;		
	-system)
		echo pour un system $2
		shift;;
	*)	echo "llexpand: Mauvaises options"
		exit ;;
    esac
    shift
done

# L'expansion elle me^me:
echo "(#:expand:expand-list-of-files #:llm3:files)">> $tmp
echo "(end)"							>> $tmp

echo "llexpand: Le LeLisp d'expansion= $BOOTLISP"
$BOOTLISP -r llcore/expdlinuxsparc.core < $tmp > /dev/null
rm -f $tmp

