;(print (libload lapvax))
(setq #:system:path (newr #:system:path
			  (if (getenv "LELISP")
			      (catenate (getenv "LELISP") "/complice/l/")
			    "/usr/ilog/lelisp/complice/l/")))
(print #:system:path)
(print (libload cp0))
(print (libload cperror))
(setq #:sys-package:colon 'complice)
(print (libload cpmac))
(print (libload peephole))
(print (libload cp1))
(print (libload cpmod1))
(print (libload cp2))
(print (libload cpenv))
(print (libload cpfnt))
(print (libload cppred))
(print (libload cpmod2))
(print (libload cp))
