echo "/* liste des drapeaux sur rs6000 */"
echo	"global.spc:	#define	Isystem rs6000"
echo	"global.spc:	#define	IX11"
echo	"global.spc:	#define	IUNIX s5"
echo	"global.spc:	#define	ISYSTEM RS6000"
echo	"global.spc:	#define	IS5"
echo	"global.spc:	#define	IRS6000"
echo	"global.spc:	#define	INOOLIT"
echo	"global.spc:	#define	INOMULTIPLECLOAD"
echo	"global.spc:	#define	INOEXECORE"
echo	"global.spc:	#define	INOEXE"
echo	"global.spc:	#define	INOCLOAD"
echo	"global.spc:	#define	INBSYST 47"
echo	"global.spc:	#define	IMOTIF"
echo	"global.spc:	#define	ILLWILDCARD"
echo	"global.spc:	#define	ILLSHAREDLIBRARIES"
echo	"global.spc:	#define	ILLSHARED"
echo	"global.spc:	#define	ILLRENAME"
echo	"global.spc:	#define	ILLNOVFORK"
echo	"global.spc:	#define	ILLNOCOERCESIGNAL"
echo	"global.spc:	#define	ILLFOREGROUND"
echo	"global.spc:	#define	IITINREAD"
echo	"global.spc:	#define	IFLOPPY"
echo	"global.spc:	#define	ICPU rs6000"
echo	"global.spc:	#define	I64BIN"
echo	"global.spc:	#define	I31BIN"
echo	"common.tmpl:	#define	sgbdFile "sgbd.spc""
echo	"common.tmpl:	#define	rpcFile "rpc.spc""
echo	"common.tmpl:	#define	UserFILESFile "UserFILES.spc""
echo	"common.tmpl:	#define	RecetteFile "Recette.tmpl""
echo	"common.tmpl:	#define	PortFILESFile "PortFILES.spc""
echo	"common.tmpl:	#define	MakeportFile "Makeport.spc""
echo	"common.tmpl:	#define	MakefileFile "Makefile.spc""
echo	"common.tmpl:	#define	IWINDOW -DX11"
echo	"common.tmpl:	#define	ILLVERSION 15.26"
echo	"common.tmpl:	#define	IDO_SUBST(f,oe,ne) `basename f oe`ne"
echo	"common.tmpl:	#define	IDO_STRING(x) &#&x&#&"
echo	"common.tmpl:	#define	IDO_NOTDEF(flg) #error %s: flg must be defined"
echo	"common.tmpl:	#define	IDO_CATENATE(x,y) x&##&y"
echo	"common.tmpl:	#define	GlobalFile "global.spc""
echo	"common.tmpl:	#define	DocInstallFile "DocInstall.spc""
echo	"Recette.tmpl:	#define	LEX11BIN leX11bin"
echo	"Recette.tmpl:	#define	LETESTBIN letestextbin"
echo	"Recette.tmpl:	#define	LELISPBIN lelispbin"
echo	"Recette.tmpl:	#define	LEBENCHBIN lelispbin"
echo	"Recette.tmpl:	#define	IVECTOR  4"
echo	"Recette.tmpl:	#define	ISYMBOL  7"
echo	"Recette.tmpl:	#define	ISTRING  8"
echo	"Recette.tmpl:	#define	ISTACK   6"
echo	"Recette.tmpl:	#define	INUMBER  0"
echo	"Recette.tmpl:	#define	IHEAP    300"
echo	"Recette.tmpl:	#define	IFLOAT   0"
echo	"Recette.tmpl:	#define	IENV "
echo	"Recette.tmpl:	#define	ICONS    24"
echo	"Recette.tmpl:	#define	ICODE  1700"
echo	"Makefile.spc:	#define	IX11_LDLIBS $(XLIB) -lX11 -liconv -lIM"
echo	"Makefile.spc:	#define	IX11_LDFLAGS $(_X11R4FLAGS)"
echo	"Makefile.spc:	#define	IMACRO_EVALOBJNAME(name) IMACRO_OBJNAME($(name))"
echo	"Makefile.spc:	#define	ILLPAGESIZE 4096"
echo	"Makefile.spc:	#define	ILINKSHARED $(CC) -T512 -H512 -e tlno -bexport:../lltest/testrs6000 -bM:SRE -o testext.sh testext.o -lm; rm -f testext.o; $(MV) testext.sh o"
echo	"Makefile.spc:	#define	ILDLIBS -lm"
echo	"Makefile.spc:	#define	ILDFLAGS -z -bro -bnso -bimport:/lib/syscalls.exp -bfl -bgcbypass:$$$$nbypass $(LOCALVARS) $(CLIB)"
echo	"Makefile.spc:	#define	IC_CFLAGS "
echo	"Makefile.spc:	#define	IBEFORELD ( set $(LLCRT0) $(IMACRO_OBJNAME($@)) ; nbypass=$$# ; \ "
echo	"Makefile.spc:	#define	IAFTERLD )"
echo	"DocInstall.spc:	#define	ITOSYSTEMARG1 X11R5"
echo	"DocInstall.spc:	#define	ITAR tar xf /dev/rfd0; sh xtract"
echo	"DocInstall.spc:	#define	IOTHEROS X11R4"
echo	"DocInstall.spc:	#define	IOS X11R5"
echo	"DocInstall.spc:	#define	IMANBSD"
echo	"DocInstall.spc:	#define	IMACHINE IBM RS/6000"
echo	"DocInstall.spc:	#define	IDF4 14000"
