(defun :test-finalize-function ()
  ;; test a simple finalization function

  (loader '((fentry #:system:finalize-function subr1)
            (push a1)
	    (push (@ 100))
	    (push '"Finalization for type: ")
	    (push (typ a1))
	    (push '" length: ")
	    (hgsize a1 a1)
	    (push a1)
	    (mov '4 a4)
	    (jmp print)
        100 (pop a1)
            (hgsize a1 a4)
	    (cnble a4 '6 101)
	    (mov '6 a4)
	101 (mov '0 a3)
            (bra 105)
	102 (push a1)
	    (push a3)
	    (push a4)
	    (push (@ 104))
	    (push '"	arg: ")
	    (push a3)
	    (push '"	")
            (hpxmov a1 a3 a2)
            (push a2)
	    (mov '4 a4)
	    (jmp print)
        104 (pop a4)
	    (pop a3)
	    (plus '1 a3)
	    (pop a1)
	105 (sobgez a4 102)
	    (return)))

  (:check-all ':test-finalize-function)
  (setq #:system:finalize-flag t))

(defun tfin ()
  (:test-finalize-function)
  (setq #:system:finalize-flag t))

