echo "/* liste des drapeaux sur solaris */"
echo	"global.spc:	#define	Isystem solaris"
echo	"global.spc:	#define	IX11"
echo	"global.spc:	#define	ISYSTEM SOLARIS"
echo	"global.spc:	#define	ISPARC"
echo	"global.spc:	#define	IPOSIX"
echo	"global.spc:	#define	INOOLIT"
echo	"global.spc:	#define	INOMULTIPLECLOAD"
echo	"global.spc:	#define	INOEXECORE"
echo	"global.spc:	#define	INOEXE"
echo	"global.spc:	#define	INOCLOAD"
echo	"global.spc:	#define	INBSYST 62"
echo	"global.spc:	#define	IMOTIF"
echo	"global.spc:	#define	ILLWILDCARD"
echo	"global.spc:	#define	ILLVFORK"
echo	"global.spc:	#define	ILLSHAREDLIBRARIES"
echo	"global.spc:	#define	ILLSHARED"
echo	"global.spc:	#define	ILLPAGESIZE 4096"
echo	"global.spc:	#define	ILLNOCOERCESIGNAL"
echo	"global.spc:	#define	ILLFOREGROUND"
echo	"global.spc:	#define	ILLELF"
echo	"global.spc:	#define	ILLBMEMALIGN(b) (char *)round((long)b+LLMAXPAGESIZE, LLMAXPAGESIZE)"
echo	"global.spc:	#define	IEXTERN_SBRK extern void *sbrk();"
echo	"global.spc:	#define	IEXTERN_BRK extern int brk();"
echo	"global.spc:	#define	ICPU sparc"
echo	"global.spc:	#define	I64BIN"
echo	"global.spc:	#define	I31BIN"
echo	"common.tmpl:	#define	sgbdFile "sgbd.spc""
echo	"common.tmpl:	#define	rpcFile "rpc.spc""
echo	"common.tmpl:	#define	UserFILESFile "UserFILES.spc""
echo	"common.tmpl:	#define	RecetteFile "Recette.tmpl""
echo	"common.tmpl:	#define	PortFILESFile "PortFILES.spc""
echo	"common.tmpl:	#define	MakeportFile "Makeport.spc""
echo	"common.tmpl:	#define	MakefileFile "Makefile.spc""
echo	"common.tmpl:	#define	IWINDOW -DX11"
echo	"common.tmpl:	#define	ILLVERSION 15.26"
echo	"common.tmpl:	#define	IDO_SUBST(f,oe,ne) `basename f oe`ne"
echo	"common.tmpl:	#define	IDO_STRING(x) &#&x&#&"
echo	"common.tmpl:	#define	IDO_NOTDEF(flg) #error %s: flg must be defined"
echo	"common.tmpl:	#define	IDO_CATENATE(x,y) x&##&y"
echo	"common.tmpl:	#define	GlobalFile "global.spc""
echo	"common.tmpl:	#define	DocInstallFile "DocInstall.spc""
echo	"Recette.tmpl:	#define	LEX11BIN leX11bin"
echo	"Recette.tmpl:	#define	LETESTBIN letestextbin"
echo	"Recette.tmpl:	#define	LELISPBIN lelispbin"
echo	"Recette.tmpl:	#define	LEBENCHBIN lelispbin"
echo	"Recette.tmpl:	#define	IVECTOR  4"
echo	"Recette.tmpl:	#define	ISYMBOL  7"
echo	"Recette.tmpl:	#define	ISTRING  8"
echo	"Recette.tmpl:	#define	ISTACK   6"
echo	"Recette.tmpl:	#define	INUMBER  0"
echo	"Recette.tmpl:	#define	IHEAP    300"
echo	"Recette.tmpl:	#define	IFLOAT   0"
echo	"Recette.tmpl:	#define	IENV "
echo	"Recette.tmpl:	#define	ICONS    24"
echo	"Recette.tmpl:	#define	ICODE  1700"
echo	"Makefile.spc:	#define	IX11_LDLIBS $(XLIB) -lX11"
echo	"Makefile.spc:	#define	ILOCALVARS"
echo	"Makefile.spc:	#define	ILINKSHARED mv testext.o o/testext.sh"
echo	"Makefile.spc:	#define	ILDLIBS -lm -lelf -lsocket -lnsl -ldl"
echo	"Makefile.spc:	#define	ILDFLAGS $(LOCALVARS) $(CLIB)"
echo	"Makefile.spc:	#define	IDO_SUBST(fc,oe,ne) $(?F:oe=ne)"
echo	"Makefile.spc:	#define	IC_CFLAGS"
echo	"Makefile.spc:	#define	ICSHARED -K PIC"
echo	"Makefile.spc:	#define	ICC /opt/SUNWspro/SC2.0.1/cc"
echo	"DocInstall.spc:	#define	ITAR tar xf /dev/rst8 \\ \$ sh xtract lelisp"
echo	"DocInstall.spc:	#define	IOS SOLARIS2.x"
echo	"DocInstall.spc:	#define	IMACHINE Sparc"
