#!/bin/sh

UNIX=NetBSD

echo You are running on Intel
if [ -f /bin/uname ]
then
echo with Unix system $UNIX: `/bin/uname -s` version `/bin/uname -r`_`/bin/uname -v`
echo based on hardware : `/bin/uname -m`
else
echo with Unix system $UNIX: NetBSD
echo based on processor 386 compatible
fi

