(deflabelval '.llstart)
(deflabelval '.nil)
(deflabelval 'bstack)
(deflabelval 'estack)
(deflabelval 'mstack)
(deflabelval 'bcode)
(deflabelval 'ccode)
(deflabelval 'ecode)
(deflabelval 'bheap)
(deflabelval 'cheap)
(deflabelval 'eheap)
(deflabelval 'bnumb)
(deflabelval 'cnumb)
(deflabelval 'bfloat)
(deflabelval 'cfloat)
(deflabelval 'bvect)
(deflabelval 'cvect)
(deflabelval 'bstrg)
(deflabelval 'cstrg)
(deflabelval 'bsymb)
(deflabelval 'csymb)
(deflabelval 'bvar)
(deflabelval 'bcons)
(deflabelval 'ccons)
(deflabelval 'bold)
(deflabelval 'eold)
(deflabelval 'fnumb)
(deflabelval 'ffloat)
(deflabelval 'fstrg)
(deflabelval 'fvect)
(deflabelval 'fsymb)
(deflabelval 'fcons)
(deflabelval 'filiz)
(deflabelval 'filit)
(deflabelval 'filin)
(deflabelval 'llban)
(deflabelval 'nbsyst)
(deflabelval 'maxchan)
(deflabelval 'itstate)
(deflabelval 'itcount)
(deflabelval 'hashtab)
(defstringval " GC_NUMB  ")
(defstringval " GC_FLOAT ")
(defstringval " GC_VECT")
(defstringval " GC_STRG")
(defstringval " GC_SYMB")
(defstringval " GC_CONS")
(defstringval " INI_HSH")
(defstringval " INI_VOI")
(defstringval " INI_NIL")
(defstringval " INI_FNT")
(defstringval " INI_TOP")
(defstringval " INI_GC ")
(defstringval " INI_PIO")
(defstringval " INI_REA")
(defstringval "INI_MACH")
(defstringval " INI_PRI")
(defstringval " INI_EVA")
(defstringval "INI_SPEC")
(defstringval " INI_CTL")
(defstringval " INI_CAD")
(defstringval " INI_SYM")
(defstringval " INI_STD")
(defstringval " INI_NBS")
(defstringval " INI_SNB")
(defstringval " INI_CHR")
(defstringval " INI_STR")
(defstringval " INI_EXT")
(defstringval " INI_BLL")
(defstringval "Que Le_Lisp soit avec vous. ")
(defstringval "; Le_Lisp (by INRIA) version 15.2 (1/Mai/87) [")
(defstringval "]")
(deflabelval 'tabsyst)
(deflabelval 'cstsyste)
(deflabelval 'unbind0)
(deflabelval 'toplevr)
(defstringval "= ")
(deflabelval 'evprognr)
(deflabelval 'unbind1)
(deflabelval 'unbind2)
(deflabelval 'unbind3)
(deflabelval 'unbind4)
(deflabelval 'unbind5)
(deflabelval 'unbind6)
(deflabelval 'unbind7)
(deflabelval 'unbind8)
(deflabelval 'unbind9)
(deflabelval 'unbind10)
(defstringval " error EVSTKF ")
(deflabelval 'llclin1)
(deflabelval 'withit1)
(deflabelval 'withno1)
(deflabelval 'userit1)
(defstringval " SAVE ")
(defstringval " STEP ")
(defstringval " REST ")
(deflabelval 'gcst00)
(defstringval " STAK ")
(defstringval " SYMB ")
(deflabelval 'gcat50)
(deflabelval 'swheap)
(defstringval "* HEAP-OVNI *")
(defstringval " SWEN ")
(defstringval " SWEF ")
(defstringval " SWEV ")
(defstringval " SWES ")
(defstringval " SWEY ")
(defstringval " GCSWSYMB ")
(defstringval " GCSWS_T3D ")
(defstringval " GCSWS_2D ")
(defstringval " GCSWS_M3D ")
(defstringval " SWEL ")
(deflabelval 'retdem)
(defstringval " FULM ")
(defstringval " GC_ON  ")
(defstringval " GC_OFF ")
(deflabelval 'frcs0)
(deflabelval 'frtr0)
(deflabelval 'send1)
(deflabelval 'gcpopj)
(deflabelval 'csend1)
(deflabelval 'ngccons)
(deflabelval 'ngcsymb)
(deflabelval 'ngcstrg)
(deflabelval 'ngcvect)
(deflabelval 'ngcfloat)
(deflabelval 'ngcnumb)
(deflabelval 'ngch)
(deflabelval 'ngcuser)
(deflabelval 'freen)
(deflabelval 'freef)
(deflabelval 'freev)
(deflabelval 'frees)
(deflabelval 'freey)
(deflabelval 'freel)
(deflabelval 'freelm)
(deflabelval 'inswcons)
(deflabelval 'swcons)
(deflabelval 'swheap)
(deflabelval 'cpheap)
(deflabelval 'oswheap)
(deflabelval 'ttytyoi1)
(deflabelval 'flulin)
(deflabelval 'istream)
(deflabelval 'ostream)
(deflabelval 'tabchan)
(deflabelval 'curinch)
(deflabelval 'curoutch)
(deflabelval 'cntrlc)
(deflabelval 'bufch)
(deflabelval 'rubstrg)
(deflabelval 'curprmpt)
(deflabelval 'ligne)
(deflabelval 'polig)
(deflabelval 'inmax)
(deflabelval 'tsymb)
(deflabelval 'asymb)
(deflabelval 'ksymb)
(deflabelval 'hsymb)
(deflabelval 'count)
(deflabelval 'tabch)
(deflabelval 'cachch)
(deflabelval 'ibase)
(deflabelval 'all09)
(deflabelval 'negatif)
(deflabelval 'quotes)
(deflabelval 'getchfl)
(deflabelval 'ringur)
(deflabelval 'curread)
(deflabelval 'rdprd)
(deflabelval 'impli)
(deflabelval 'impld)
(deflabelval 'bufat)
(deflabelval 'cpkgc)
(deflabelval 'trysymb)
(deflabelval 'trysymp1)
(deflabelval 'trysymbx)
(deflabelval 'tgetcv)
(deflabelval 'tgetcv)
(deflabelval 'getcv3)
(deflabelval 'rdtb1)
(deflabelval 'rdtb1)
(deflabelval 'readi)
(deflabelval 'readt1)
(deflabelval 'readt1)
(deflabelval 'readt2)
(deflabelval 'readt2)
(deflabelval 'read4)
(deflabelval 'readt3)
(deflabelval 'readt3)
(deflabelval 'asciii)
(deflabelval 'fascii8)
(deflabelval 'tabctyp)
(deflabelval 'tabccod)
(deflabelval 'dmcret)
(deflabelval 'llbquot1)
(deflabelval 'commain)
(deflabelval 'shrpdot1)
(deflabelval 'shrpcol1)
(deflabelval 'shrpbar)
(deflabelval 'shrpbra1)
(deflabelval 'rdpkgc2)
(deflabelval 'typtab)
(deflabelval 'typtab)
(deflabelval 'bufout)
(deflabelval 'bufpn)
(deflabelval 'obase)
(deflabelval 'prmdp)
(deflabelval 'prcdp)
(deflabelval 'prmlp)
(deflabelval 'prclp)
(deflabelval 'prmln)
(deflabelval 'prcln)
(deflabelval 'prmpk)
(deflabelval 'prcpk)
(deflabelval 'sprint)
(deflabelval 'pocour)
(deflabelval 'nbleft)
(deflabelval 'nbrig)
(deflabelval 'maxpocou)
(deflabelval 'iexpld)
(deflabelval 'lexpld)
(deflabelval 'prpkg0)
(deflabelval 'prsymb)
(deflabelval 'prpopj)
(deflabelval 'chklp)
(deflabelval 'explode1)
(deflabelval 'llink)
(deflabelval 'evalst)
(deflabelval 'forme)
(deflabelval 'funct)
(deflabelval 'savea1)
(deflabelval 'savea2)
(deflabelval 'savea3)
(deflabelval 'savea4)
(deflabelval 'errname)
(deflabelval 'intret)
(deflabelval 'intllink)
(deflabelval 'dlink)
(deflabelval 'evala1)
(deflabelval 'stepevr)
(deflabelval 'teval)
(deflabelval 'teval)
(deflabelval 'evaldmr)
(deflabelval 'evexpg)
(deflabelval 'popj)
(deflabelval 'tfuncall)
(deflabelval 'tfuncall)
(defstringval " error UNBINP ")
(deflabelval 'unbides2)
(deflabelval 'evesc1)
(deflabelval 'uvesc1)
(deflabelval 'unwind4)
(deflabelval 'savits)
(defstringval " error SUSPN ")
(deflabelval 'susb13)
(deflabelval 'restes)
(deflabelval 'llgof8)
(deflabelval 'llretr3)
(deflabelval 'cwithit1)
(deflabelval 'cwithno1)
(deflabelval 'tabtypfn)
(deflabelval 'tabcodfn)
(deflabelval 'tbmakdef)
(deflabelval 'tbmakdef)
(deflabelval 'map1)
(deflabelval 'mapun1)
(deflabelval 'map6)
(deflabelval 'mapun6)
(deflabelval 'map7)
(deflabelval 'mapun7)
(deflabelval 'mapun8)
(deflabelval 'map8)
(deflabelval 'mapun9)
(deflabelval 'map9)
(deflabelval 'mapvect2)
(deflabelval 'mapcobco)
(deflabelval 'maplobco)
(deflabelval 'mapcob5)
(deflabelval 'llnot)
(deflabelval 'setplist)
(deflabelval 'pckgset)
(deflabelval 'objvset)
(deflabelval 'moinsun)
(deflabelval 'fzero)
(deflabelval 'fltun)
(deflabelval 'fltmun)
(deflabelval 'fltimax)
(deflabelval 'fltimin)
(deflabelval 'cpfnt)
(deflabelval 'gadiffp)
(deflabelval 'gadivt)
(deflabelval 'oneret)
(deflabelval 'tworet)
(deflabelval 'gaeqnret)
(deflabelval 'randseed)
(deflabelval 'ocheap)
(deflabelval 'concat9)
(deflabelval 'scrnaff3)
(deflabelval 'wd)
(deflabelval 'ws)
(deflabelval 'dlx)
(deflabelval 'dly)
(deflabelval 'oldid)
(deflabelval 'oldx)
(deflabelval 'id)
(deflabelval 'is)
(deflabelval 'xr)
(deflabelval 'yr)
(deflabelval 'ys)
(deflabelval 'memory2)
